AWSTemplateFormatVersion: "2010-09-09"
Description: 
  Amazon Elasticsearch Service Create

Parameters:
  ESDomainName:
    Description: "Your Elasticsearch Domain Name"
    Default: testdomain
    Type: String
    MinLength: 3
    MaxLength: 28
    AllowedPattern: "^[a-z0-9+-]*$"

  PJPrefix:
    Default: "test"
    Type: String

Resources:
  MyElasticSearch:
    Type: AWS::Elasticsearch::Domain
    Properties:
      DomainName: !Ref ESDomainName
      ElasticsearchVersion: 7.10
      ElasticsearchClusterConfig:
        DedicatedMasterEnabled: false
        InstanceCount: 1
        InstanceType: t3.small.elasticsearch
        ZoneAwarenessEnabled: false
        WarmEnabled: false
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: 
            AWS: '*'
          Action: 
          - es:*
          Resource: 
          -  !Sub arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${ESDomainName}/*

      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10
        VolumeType: gp2

      VPCOptions:
        SubnetIds:
        - Fn::ImportValue: !Sub "${PJPrefix}-ES-subnet-a"
        #- Fn::ImportValue: !Sub "${PJPrefix}-ES-subnet-c"
        #- Fn::ImportValue: !Sub "${PJPrefix}-ES-subnet-d"
        SecurityGroupIds:
        - Fn::ImportValue: !Sub "${PJPrefix}-ES-sg"