AWSTemplateFormatVersion: "2010-09-09"
Description: This Template Creates WebACL For Cloudfront. Deploy At Global
Resources:
  MyWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: testWaf
      Description: create a testWaf
      DefaultAction: 
        Type: Allow
      Rules: 
      -  Name: AWS-AWSManagedRulesAmazonIpReputationList
         Priority: 1
         Statement:
           ManagedRuleGroupStatement:
             VendorName: AWS
             Name: AWSManagedRulesAmazonIpReputationList
         OverrideAction: 
           None: {}
         VisibilityConfig: 
           SampledRequestsEnabled: true
           CloudWatchMetricsEnabled: true
           MetricName: AWS-AWSManagedRulesAmazonIpReputationList

      -  Name: AWS-AWSManagedRulesAnonymousIpList
         Priority: 2
         Statement:
           ManagedRuleGroupStatement:
             VendorName: AWS
             Name: AWSManagedRulesAnonymousIpList
         OverrideAction: 
           None: {}
         VisibilityConfig: 
           SampledRequestsEnabled: true
           CloudWatchMetricsEnabled: true
           MetricName: AWS-AWSManagedRulesAnonymousIpList

      #-  Name: AWS-AWSManagedRulesBotControlRuleSet
      #   Priority: 3
      #   Statement:
      #     ManagedRuleGroupStatement:
      #       VendorName: AWS
      #       Name: AWSManagedRulesBotControlRuleSet
      #   OverrideAction: 
      #     None: {}
      #   VisibilityConfig: 
      #     SampledRequestsEnabled: true
      #     CloudWatchMetricsEnabled: true
      #     MetricName: AWS-AWSManagedRulesBotControlRuleSet

      -  Name: AWS-AWSManagedRulesSQLiRuleSet
         Priority: 4
         Statement:
           ManagedRuleGroupStatement:
             VendorName: AWS
             Name: AWSManagedRulesSQLiRuleSet
         OverrideAction: 
           None: {}
         VisibilityConfig: 
           SampledRequestsEnabled: true
           CloudWatchMetricsEnabled: true
           MetricName: AWS-AWSManagedRulesSQLiRuleSet

      -  Name: AWS-AWSManagedRulesKnownBadInputsRuleSet
         Priority: 5
         Statement:
           ManagedRuleGroupStatement:
             VendorName: AWS
             Name: AWSManagedRulesKnownBadInputsRuleSet
         OverrideAction: 
           None: {}
         VisibilityConfig: 
           SampledRequestsEnabled: true
           CloudWatchMetricsEnabled: true
           MetricName: AWS-AWSManagedRulesKnownBadInputsRuleSet

      -  Name: AWS-AWSManagedRulesCommonRuleSet
         Priority: 6
         Statement:
           ManagedRuleGroupStatement:
             VendorName: AWS
             Name: AWSManagedRulesCommonRuleSet
         OverrideAction: 
           None: {}
         VisibilityConfig: 
           SampledRequestsEnabled: true
           CloudWatchMetricsEnabled: true
           MetricName: AWS-AWSManagedRulesCommonRuleSet
 